name: TextEditorWeb

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O TextEditorWeb/google-secret.json ${{ secrets.GIST_URL }}
        
    - name: Build and deploy the Docker image
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'text-editor-web' }}
      run: |
        cd TextEditorWeb
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
